name: Check PR

on:
  pull_request:
    types: [opened, edited]

jobs:

  check-branches:
    name: Check base branch and branch name
    runs-on: ubuntu-latest
    steps:
      - uses: semestry/git-flow-action@v1
        env:
          GITHUB_TOKEN:  ${{ secrets.GIT_FLOW_ACTION_PAT }}
